import Head from "next/head";
import React from "react";
import { Navbar } from "../../components/Navbar";
import { ProductItem } from "../../components/ProductItem";
import { Sidebar } from "../../components/Sidebar";
import { Footer } from "../../components/Footer";
import { MenuItem } from "../../components/MenuItem";

export default function index() {
  const titles = [
    { title: "ID", img: "/id.svg" },
    { title: "Product", img: "/goods-contents.svg" },
    { title: "Stock", img: "/stock.svg" },
    { title: "Price", img: "/price.svg" },
    { title: "Action", img: "/object.svg" },
  ];

  return (
    <>
      <Head>
        <title>Products - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar className="h-1/5" />
      <main className="flex flex-row justify-center">
        <Sidebar />
        <div className="flex flex-col mt-2 mr-6 w-5/6 border-slate-400 border-2 rounded-lg drop-shadow-lg shadow-sm shadow-slate-500 p-10">
          <div className="flex flex-row justify-between p-4 mr-4">
            {titles.map((item) => {
              return (
                <MenuItem key={item.title} item={item} />
              );
            })}
          </div>

          <ProductItem />
          <ProductItem />
          <ProductItem />
          <ProductItem />

          <div className="flex items-center justify-center mt-4 mb-4">
            <span className="pl-2 pr-2 pt-3 pb-2 bg-purple-500/70 hover:bg-purple-500/60  font-semibold text-base rounded-md text-center cursor-pointer">
              Add a new product
            </span>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
