import Head from "next/head";
import React from "react";
import { Footer } from "../../components/Footer";
import { MenuItem } from "../../components/MenuItem";
import { Navbar } from "../../components/Navbar";
import { Sidebar } from "../../components/Sidebar";
import { UserItem } from "../../components/UserItem";

export default function index() {
  const titles = [
    { title: "ID", img: "/id.svg" },
    { title: "Username", img: "/female-user.svg" },
    { title: "Email", img: "/email-round-solid.svg" },
    { title: "Status", img: "/status.svg" },
    { title: "Transactions", img: "/money-spent.svg" },
  ];
  return (
    <>
      <Head>
        <title>Users - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-row justify-center">
        <Sidebar />
        <div className="flex flex-col mt-2 mr-6 w-5/6 border-slate-400 border-2 rounded-lg drop-shadow-lg shadow-sm shadow-slate-500 p-10">
          <div className="flex flex-row justify-between p-4">
            {titles.map((item) => {
              return <MenuItem key={item.title} item={item} />;
            })}
          </div>

          <UserItem />
          <UserItem />
          <UserItem />
          <UserItem />
          <UserItem />
          <UserItem />
        </div>
      </main>
      <Footer />
    </>
  );
}
